### ISSUE TITLE
the output command not seemingly working

### ISSUE THREAD

**Issue by Tom-Mann** [gator1/terraform-provider-opentelekomcloud#19]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
v0.10.8

### Affected Resource(s)
Please list the resources as a list, for example:
- otc_instance
- otc_storage_volume
- otc_dns
- output

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "openstack_dns_recordset_v2" "server_dns" {
  count   = "1"
  zone_id = "${var.zoneID}"
  name    = "${var.name_prefix}-PD.${var.Environment}.${var.domainName}"
  type    = "A"
  records = ["${element(opentelekomcloud_compute_instance_v2.server.*.access_ip_v4, count.index)}"]
}

output "server_fqdn" {
  value = "${openstack_dns_recordset_v2.server_dns.name}"
}

### Expected Behavior
What should have happened?

it should export the name of the server

### Actual Behavior
What actually happened?

it says that no outputs defined

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. 'terraform output'
3. reports no output to report

**Comment by huangtianhua** [comment]
Hi,
Sorry to reply so late.
I took a test for it,  and the result is ok, we can get the name of record set, the tf file I used you can find in http://paste.openstack.org/show/645659/ and the log of  'terraform apply' is in http://paste.openstack.org/show/645658/

Also, we can get the output by executing cmd 'terraform output':
root@hth:~/go/bin/otc-eu-de-lizhonghua# terraform output
prizone_record_name = 1.1.hth.prizone.com.
pubzone_record_name = ns-pd.hth.pubzone.com.

So I  could you check it again,  to make sure the dns recordset is created successfully. 
ps:  I met a problem before: if the record set name is not end with zone name, the record set won't be created successful, then we can't get the name for it.

**Comment by huangtianhua** [comment]
Execute cmd ‘terraform output –module=Tester’ will get the outputs for resources within the module 'Tester'.
