### ISSUE TITLE
Error while trying to delete instance

### ISSUE THREAD

**Issue by mvasilenko** [gator1/terraform-provider-opentelekomcloud#33]
Hi there,

### Terraform Version
```
Terraform v0.11.3
+ provider.null v1.0.0
+ provider.opentelekomcloud (unversioned)
+ provider.template v1.0.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_networking_router_interface_v2.interface
- opentelekomcloud_compute_volume_attach_v2.volume_attach

### Terraform Configuration Files
```hcl
# credentials
provider "opentelekomcloud" {
  user_name   = "${var.username}"
  password    = "${var.password}"
  tenant_name = "${var.tenant_name}"
  domain_name = "${var.domain_name}"
  auth_url    = "${var.endpoint}"
}

# instance image
data "opentelekomcloud_images_image_v2" "sd_image" {
  name = "${var.image_name}"

}
# create instance
resource "opentelekomcloud_compute_instance_v2" "sd_test_instance" {
  count           = "1"
  name            = "${var.dnszone}"
  image_name      = "${var.image_name}"
  flavor_name     = "s1.medium"
  key_pair        = "mvasilenko-mbp15"
  security_groups = [
    "${opentelekomcloud_compute_secgroup_v2.secgrp_web.name}"
  ]

  network {
    uuid           = "${opentelekomcloud_networking_network_v2.otc_test_network.id}"
  }

}
# attach volume to the instance
resource "opentelekomcloud_compute_volume_attach_v2" "volume_attach" {
  count       = "1"
  instance_id = "${opentelekomcloud_compute_instance_v2.sd_test_instance.id}"
  volume_id   = "${opentelekomcloud_blockstorage_volume_v2.sd_test_data_disk.id}"
}
# create dns zone
resource "opentelekomcloud_dns_zone_v2" "dnszone" {
  name  = "${var.dnszone}"
  email = "info@${var.dnszone}"
  ttl   = 6000
}
# A record for instance
resource "opentelekomcloud_dns_recordset_v2" "test_a" {
  zone_id = "${opentelekomcloud_dns_zone_v2.dnszone.id}"
  name    = "${var.dnszone}"
  ttl     = 300
  type    = "A"
  records = ["${opentelekomcloud_networking_floatingip_v2.floatip_test_addr.address}"]
}
# create network
resource "opentelekomcloud_networking_network_v2" "otc_test_network" {
  count          = "1"
  name           = "${var.dnsname}-network"
  admin_state_up = "true"
}
# create subnet
resource "opentelekomcloud_networking_subnet_v2" "otc_test_subnet" {
  name            = "${var.dnsname}-subnet"
  count           = "1"
  network_id      = "${opentelekomcloud_networking_network_v2.otc_test_network.id}"
  cidr            = "${var.subnet_cidr}"
  ip_version      = 4
  dns_nameservers = ["8.8.8.8", "8.8.4.4"]
}

# get external IP
resource "opentelekomcloud_networking_floatingip_v2" "floatip_test_addr" {
  pool = "admin_external_net"
}

# attach it to SSH server
resource "opentelekomcloud_compute_floatingip_associate_v2" "floatip_test_map" {
  floating_ip = "${opentelekomcloud_networking_floatingip_v2.floatip_test_addr.address}"
  instance_id = "${opentelekomcloud_compute_instance_v2.sd_test_instance.id}"
}
# create router
resource "opentelekomcloud_networking_router_v2" "otc_test_router" {
  count            = "1"
  name             = "${var.dnsname}-router"
  admin_state_up   = "true"
  external_gateway = "0a2228f2-7f8a-45f1-8e09-9039e1d09975"
}
# attach subnet to the router
resource "opentelekomcloud_networking_router_interface_v2" "interface" {
  count     = "${var.instance_count}"
  router_id = "${opentelekomcloud_networking_router_v2.otc_test_router.id}"
  subnet_id = "${opentelekomcloud_networking_subnet_v2.otc_test_subnet.id}"
}
resource "opentelekomcloud_compute_secgroup_v2" "secgrp_web" {
  count       = "${var.instance_count}"
  name        = "${var.dnsname}-secgrp"
  description = "${var.dnsname} Security Group"

  rule {
    from_port   = 22
    to_port     = 22
    ip_protocol = "tcp"
    cidr        = "0.0.0.0/0"
  }

  rule {
    from_port   = 80
    to_port     = 80
    ip_protocol = "tcp"
    cidr        = "0.0.0.0/0"
  }

  rule {
    from_port   = 443
    to_port     = 443
    ip_protocol = "tcp"
    cidr        = "0.0.0.0/0"
  }

  rule {
    from_port   = -1
    to_port     = -1
    ip_protocol = "icmp"
    cidr        = "0.0.0.0/0"
  }
}

### OpenTelekomCloud Credentials
variable "username" {
  # If you don't fill this in, you will be prompted for it
  #default = "your_username"
}

variable "password" {
  # If you don't fill this in, you will be prompted for it
  #default = "your_password'
}

variable "domain_name" {
  # If you don't fill this in, you will be prompted for it
  #default = "your_domainname"
}

variable "tenant_name" {
  default = "eu-de"
}

variable "endpoint" {
  default = "https://iam.eu-de.otc.t-systems.com:443/v3"
}

### OTC Specific Settings
variable "external_network" {
  default = "admin_external_net"
}

variable "subnet_cidr" {
  default = "192.168.13.0/24"
}

variable "ssh_pub_key" {
  default = "~/.ssh/id_rsa.pub"
}


### VM (Instance) Settings
variable "instance_count" {
  default = "1"
}

variable "disk_size_gb" {
  default = "5"
}

variable "flavor_name" {
  default = "s1.medium"
}

variable "image_name" {
  default = "Community_Ubuntu_16.04_TSI_latest"
}


```

### Debug Output

brief output

```
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still destroying... (ID: 95f8a2b1-a947-453e-877f-a119cabc7fc6/8bbf9ef1-05e5-41eb-bb79-b03f0d9dd671, 4m10s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still destroying... (ID: 95f8a2b1-a947-453e-877f-a119cabc7fc6/8bbf9ef1-05e5-41eb-bb79-b03f0d9dd671, 4m20s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still destroying... (ID: 95f8a2b1-a947-453e-877f-a119cabc7fc6/8bbf9ef1-05e5-41eb-bb79-b03f0d9dd671, 4m30s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* opentelekomcloud_compute_volume_attach_v2.volume_attach (destroy): 1 error(s) occurred:

* opentelekomcloud_compute_volume_attach_v2.volume_attach: Error detaching OpenTelekomCloud volume: couldn't find resource (21 retries)
```

Here is volume status while running terraform

```
$ openstack volume list
+--------------------------------------+------------------------+-----------+------+-------------------------------------------------+
| ID                                   | Name                   | Status    | Size | Attached to                                     |
+--------------------------------------+------------------------+-----------+------+-------------------------------------------------+
| fedfbc27-af6d-4b7f-9f0c-11eb94fcb2ae | otc-test.smashdocs.net | in-use    |   12 | Attached to otc-test.smashdocs.net on /dev/sda  |
| 8bbf9ef1-05e5-41eb-bb79-b03f0d9dd671 | otc-test-data-disk     | detaching |    5 | Attached to otc-test.smashdocs.net on /dev/sdb  |
```

### Expected Behavior
instance deleted

### Actual Behavior
error reported

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform destroy`

**Comment by 28formica77** [comment]
Hi Mikhail,

I can't see where you create your data disk. Also, I can't see where you specify the availability zone. If the disk is not in the same availability zone as the VM, you won't be able to attach it.

Can you try updating it like this?

# create instance
resource "opentelekomcloud_compute_instance_v2" "sd_test_instance" {
  count           = "1"
  name            = "${var.dnszone}"
  image_name      = "${var.image_name}"
  flavor_name     = "s1.medium"
  key_pair        = "terraform_key"
  security_groups = [
    "${opentelekomcloud_compute_secgroup_v2.secgrp_web.name}"
  ]
  availability_zone ="eu-de-01"

  network {
    uuid           = "${opentelekomcloud_networking_network_v2.otc_test_network.id}"
  }

}

#Create the  Data volume
resource "opentelekomcloud_blockstorage_volume_v2" "sd_test_data_disk" {
  count = "1"
  availability_zone ="eu-de-01"
  name  = "test-data-disk"
  size  = "10"
}

opentelekomcloud_blockstorage_volume_v2.sd_test_data_disk: Creation complete after 14s (ID: 5152b9ba-50b0-4470-943b-44e555aacb16)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (10s elapsed)
opentelekomcloud_networking_router_interface_v2.interface: Creation complete after 7s (ID: 04593379-5613-4a70-a042-d313019eea8a)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (20s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (30s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (40s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (50s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m0s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m10s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m20s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m30s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m40s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Creation complete after 1m41s (ID: 1ebc610b-33eb-43d7-bf84-559b141a0025)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Creating...
  instance_id: "" => "1ebc610b-33eb-43d7-bf84-559b141a0025"
  region:      "" => "<computed>"
  volume_id:   "" => "5152b9ba-50b0-4470-943b-44e555aacb16"
opentelekomcloud_compute_floatingip_associate_v2.floatip_test_map: Creating...
  floating_ip: "" => "80.158.4.192"
  instance_id: "" => "1ebc610b-33eb-43d7-bf84-559b141a0025"
  region:      "" => "<computed>"
opentelekomcloud_compute_floatingip_associate_v2.floatip_test_map: Creation complete after 5s (ID: 80.158.4.192/1ebc610b-33eb-43d7-bf84-559b141a0025/)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (10s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (20s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (30s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Creation complete after 36s (ID: 1ebc610b-33eb-43d7-bf84-559b141a0025/5152b9ba-50b0-4470-943b-44e555aacb16)

**Comment by mvasilenko** [comment]
Sorry, @28formica77 forgot to include attachment part, it's pretty standard

```
resource "opentelekomcloud_compute_volume_attach_v2" "volume_attach" {
  count       = "1"
  instance_id = "${opentelekomcloud_compute_instance_v2.sd_test_instance.id}"
  volume_id   = "${opentelekomcloud_blockstorage_volume_v2.sd_test_data_disk.id}"
}
```
my instance lifecycle:

**Initial instance creation** - `terraform apply`
* create instance with specified `user-data` (app provisioning)
* create data disk for persistent data
* start instance, attach data disk to instance

**Update app version**
* update `user-data` (bump app version)
* run `terraform apply` - it will try to 

- detach floating ip from instance
- destroy dns record
- detach data disk <-- terraform fails here
- destroy instance
- create new instance with updated `user-data`
- attach data disk with persistent data
- attach floating ip
- create dns record

I'm new to OpenTelekomCloud, but as far as I understood, instance must be stopped before volume detachment, and `terraform` is not stopping instance before trying to detach volume, so the provisioning fails. 

If I stop instance by `otc` tool or `openstack server stop`, before running `terraform apply`,  provisioning goes fine.

Guest OS is Ubuntu 16 x64

Is there any workaround for that?

**Comment by 28formica77** [comment]
Hi Mikhail,

Actually, you did include the attach, it was the volume that was missing. It works for me though. I added user_data, ran it once, made a change and ran it again.

Have you compile the driver from this repo, and copy it to ~/.terraform.d/plugins/terraform-provider-opentelekomcloud, or are you using another version?

[linux@BastionHost tfmikhail]$ make apply
terraform apply -var-file=parameter.tvars
data.opentelekomcloud_images_image_v2.sd_image: Refreshing state...
opentelekomcloud_networking_network_v2.otc_test_network: Creating...
  admin_state_up: "" => "true"
  name:           "" => "testserver-network"
  region:         "" => "<computed>"
  shared:         "" => "<computed>"
  tenant_id:      "" => "<computed>"
opentelekomcloud_networking_floatingip_v2.floatip_test_addr: Creating...
  address:   "" => "<computed>"
  fixed_ip:  "" => "<computed>"
  pool:      "" => "admin_external_net"
  port_id:   "" => "<computed>"
  region:    "" => "<computed>"
  tenant_id: "" => "<computed>"
opentelekomcloud_blockstorage_volume_v2.sd_test_data_disk: Creating...
  attachment.#:      "" => "<computed>"
  availability_zone: "" => "eu-de-01"
  metadata.%:        "" => "<computed>"
  name:              "" => "test-data-disk"
  region:            "" => "<computed>"
  size:              "" => "10"
  volume_type:       "" => "<computed>"
opentelekomcloud_networking_router_v2.otc_test_router: Creating...
  admin_state_up:   "" => "true"
  distributed:      "" => "<computed>"
  external_gateway: "" => "0a2228f2-7f8a-45f1-8e09-9039e1d09975"
  name:             "" => "testserver-router"
  region:           "" => "<computed>"
  tenant_id:        "" => "<computed>"
opentelekomcloud_dns_zone_v2.dnszone: Creating...
  email:     "" => "info@testmikhail.com"
  masters.#: "" => "<computed>"
  name:      "" => "testmikhail.com"
  region:    "" => "<computed>"
  ttl:       "" => "6000"
  zone_type: "" => "public"
opentelekomcloud_compute_secgroup_v2.secgrp_web: Creating...
  description:                   "" => "testserver Security Group"
  name:                          "" => "testserver-secgrp"
  region:                        "" => "<computed>"
  rule.#:                        "" => "4"
  rule.2180185248.cidr:          "" => "0.0.0.0/0"
  rule.2180185248.from_group_id: "" => ""
  rule.2180185248.from_port:     "" => "-1"
  rule.2180185248.id:            "" => "<computed>"
  rule.2180185248.ip_protocol:   "" => "icmp"
  rule.2180185248.self:          "" => "false"
  rule.2180185248.to_port:       "" => "-1"
  rule.3211544828.cidr:          "" => "0.0.0.0/0"
  rule.3211544828.from_group_id: "" => ""
  rule.3211544828.from_port:     "" => "443"
  rule.3211544828.id:            "" => "<computed>"
  rule.3211544828.ip_protocol:   "" => "tcp"
  rule.3211544828.self:          "" => "false"
  rule.3211544828.to_port:       "" => "443"
  rule.3719211069.cidr:          "" => "0.0.0.0/0"
  rule.3719211069.from_group_id: "" => ""
  rule.3719211069.from_port:     "" => "80"
  rule.3719211069.id:            "" => "<computed>"
  rule.3719211069.ip_protocol:   "" => "tcp"
  rule.3719211069.self:          "" => "false"
  rule.3719211069.to_port:       "" => "80"
  rule.836640770.cidr:           "" => "0.0.0.0/0"
  rule.836640770.from_group_id:  "" => ""
  rule.836640770.from_port:      "" => "22"
  rule.836640770.id:             "" => "<computed>"
  rule.836640770.ip_protocol:    "" => "tcp"
  rule.836640770.self:           "" => "false"
  rule.836640770.to_port:        "" => "22"
opentelekomcloud_compute_secgroup_v2.secgrp_web: Creation complete after 2s (ID: f4de919f-60e2-44f6-967f-aad94126f53c)
opentelekomcloud_dns_zone_v2.dnszone: Creation complete after 5s (ID: ff80808261418b240161f701d4c63d9d)
opentelekomcloud_networking_network_v2.otc_test_network: Creation complete after 6s (ID: ab9f2778-841b-4414-aa1e-3025ce04b820)
opentelekomcloud_compute_instance_v2.sd_test_instance: Creating...
  access_ip_v4:              "" => "<computed>"
  access_ip_v6:              "" => "<computed>"
  all_metadata.%:            "" => "<computed>"
  availability_zone:         "" => "eu-de-01"
  flavor_id:                 "" => "<computed>"
  flavor_name:               "" => "s1.medium"
  image_id:                  "" => "<computed>"
  image_name:                "" => "Community_Ubuntu_16.04_TSI_latest"
  key_pair:                  "" => "terraform_key"
  name:                      "" => "testmikhail.com"
  network.#:                 "" => "1"
  network.0.access_network:  "" => "false"
  network.0.fixed_ip_v4:     "" => "<computed>"
  network.0.fixed_ip_v6:     "" => "<computed>"
  network.0.floating_ip:     "" => "<computed>"
  network.0.mac:             "" => "<computed>"
  network.0.name:            "" => "<computed>"
  network.0.port:            "" => "<computed>"
  network.0.uuid:            "" => "ab9f2778-841b-4414-aa1e-3025ce04b820"
  region:                    "" => "<computed>"
  security_groups.#:         "" => "1"
  security_groups.821539756: "" => "testserver-secgrp"
  stop_before_destroy:       "" => "false"
  user_data:                 "" => "452b9ef6128065e9e0329ba8d32daf9715595fa4"
opentelekomcloud_networking_subnet_v2.otc_test_subnet: Creating...
  allocation_pools.#:         "" => "<computed>"
  cidr:                       "" => "192.168.13.0/24"
  dns_nameservers.#:          "" => "2"
  dns_nameservers.3811298194: "" => "8.8.4.4"
  dns_nameservers.3817307869: "" => "8.8.8.8"
  enable_dhcp:                "" => "true"
  gateway_ip:                 "" => "<computed>"
  ip_version:                 "" => "4"
  name:                       "" => "testserver-subnet"
  network_id:                 "" => "ab9f2778-841b-4414-aa1e-3025ce04b820"
  region:                     "" => "<computed>"
  tenant_id:                  "" => "<computed>"
opentelekomcloud_networking_floatingip_v2.floatip_test_addr: Creation complete after 6s (ID: ec27d19f-cf7e-4453-ac69-7bd7ecc16a07)
opentelekomcloud_dns_recordset_v2.test_a: Creating...
  name:      "" => "testmikhail.com"
  records.#: "" => "1"
  records.0: "" => "80.158.7.123"
  region:    "" => "<computed>"
  ttl:       "" => "300"
  type:      "" => "A"
  zone_id:   "" => "ff80808261418b240161f701d4c63d9d"
opentelekomcloud_networking_router_v2.otc_test_router: Creation complete after 7s (ID: 53437f8b-2bbf-40a8-9105-d23816cd617a)
opentelekomcloud_blockstorage_volume_v2.sd_test_data_disk: Still creating... (10s elapsed)
opentelekomcloud_networking_subnet_v2.otc_test_subnet: Creation complete after 6s (ID: 3b8f6ebc-a89a-48b8-8e05-95c9ea3461f7)
opentelekomcloud_networking_router_interface_v2.interface: Creating...
  region:    "" => "<computed>"
  router_id: "" => "53437f8b-2bbf-40a8-9105-d23816cd617a"
  subnet_id: "" => "3b8f6ebc-a89a-48b8-8e05-95c9ea3461f7"
opentelekomcloud_blockstorage_volume_v2.sd_test_data_disk: Creation complete after 13s (ID: ad4e5045-1a26-4750-91e0-be759f2ea4d7)
opentelekomcloud_dns_recordset_v2.test_a: Creation complete after 8s (ID: ff80808261418b240161f701d4c63d9d/ff80808261418b820161f701eef13f37)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (10s elapsed)
opentelekomcloud_networking_router_interface_v2.interface: Creation complete after 8s (ID: 7e802afe-2c26-4e0e-a4e4-41660bd9c9b0)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (20s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (30s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (40s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (50s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m0s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m10s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m20s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m30s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m40s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Creation complete after 1m42s (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Creating...
  instance_id: "" => "b37bca77-dd2c-452a-81af-7c9cfeb83e27"
  region:      "" => "<computed>"
  volume_id:   "" => "ad4e5045-1a26-4750-91e0-be759f2ea4d7"
opentelekomcloud_compute_floatingip_associate_v2.floatip_test_map: Creating...
  floating_ip: "" => "80.158.7.123"
  instance_id: "" => "b37bca77-dd2c-452a-81af-7c9cfeb83e27"
  region:      "" => "<computed>"
opentelekomcloud_compute_floatingip_associate_v2.floatip_test_map: Creation complete after 5s (ID: 80.158.7.123/b37bca77-dd2c-452a-81af-7c9cfeb83e27/)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (10s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (20s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (30s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Creation complete after 36s (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27/ad4e5045-1a26-4750-91e0-be759f2ea4d7)

Apply complete! Resources: 12 added, 0 changed, 0 destroyed.
[linux@BastionHost tfmikhail]$ 
[linux@BastionHost tfmikhail]$ 
[linux@BastionHost tfmikhail]$ vi mk.tf 
[linux@BastionHost tfmikhail]$ make apply
terraform apply -var-file=parameter.tvars
opentelekomcloud_networking_router_v2.otc_test_router: Refreshing state... (ID: 53437f8b-2bbf-40a8-9105-d23816cd617a)
opentelekomcloud_dns_zone_v2.dnszone: Refreshing state... (ID: ff80808261418b240161f701d4c63d9d)
opentelekomcloud_blockstorage_volume_v2.sd_test_data_disk: Refreshing state... (ID: ad4e5045-1a26-4750-91e0-be759f2ea4d7)
opentelekomcloud_compute_secgroup_v2.secgrp_web: Refreshing state... (ID: f4de919f-60e2-44f6-967f-aad94126f53c)
opentelekomcloud_networking_network_v2.otc_test_network: Refreshing state... (ID: ab9f2778-841b-4414-aa1e-3025ce04b820)
opentelekomcloud_networking_floatingip_v2.floatip_test_addr: Refreshing state... (ID: ec27d19f-cf7e-4453-ac69-7bd7ecc16a07)
data.opentelekomcloud_images_image_v2.sd_image: Refreshing state...
opentelekomcloud_networking_subnet_v2.otc_test_subnet: Refreshing state... (ID: 3b8f6ebc-a89a-48b8-8e05-95c9ea3461f7)
opentelekomcloud_compute_instance_v2.sd_test_instance: Refreshing state... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27)
opentelekomcloud_dns_recordset_v2.test_a: Refreshing state... (ID: ff80808261418b240161f701d4c63d9d/ff80808261418b820161f701eef13f37)
opentelekomcloud_networking_router_interface_v2.interface: Refreshing state... (ID: 7e802afe-2c26-4e0e-a4e4-41660bd9c9b0)
opentelekomcloud_compute_floatingip_associate_v2.floatip_test_map: Refreshing state... (ID: 80.158.7.123/b37bca77-dd2c-452a-81af-7c9cfeb83e27/)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Refreshing state... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27/ad4e5045-1a26-4750-91e0-be759f2ea4d7)
opentelekomcloud_compute_floatingip_associate_v2.floatip_test_map: Destroying... (ID: 80.158.7.123/b37bca77-dd2c-452a-81af-7c9cfeb83e27/)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Destroying... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27/ad4e5045-1a26-4750-91e0-be759f2ea4d7)
opentelekomcloud_dns_recordset_v2.test_a: Destroying... (ID: ff80808261418b240161f701d4c63d9d/ff80808261418b820161f701eef13f37)
opentelekomcloud_compute_floatingip_associate_v2.floatip_test_map: Destruction complete after 3s
opentelekomcloud_dns_recordset_v2.test_a: Destruction complete after 5s
opentelekomcloud_dns_zone_v2.dnszone: Destroying... (ID: ff80808261418b240161f701d4c63d9d)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still destroying... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27/ad4e5045-1a26-4750-91e0-be759f2ea4d7, 10s elapsed)
opentelekomcloud_dns_zone_v2.dnszone: Destruction complete after 5s
opentelekomcloud_dns_zone_v2.dnszone: Creating...
  email:     "" => "info@testmikhail.com"
  masters.#: "" => "<computed>"
  name:      "" => "testmikhail.com"
  region:    "" => "<computed>"
  ttl:       "" => "6000"
  zone_type: "" => "public"
opentelekomcloud_dns_zone_v2.dnszone: Creation complete after 5s (ID: ff80808261418b820161f704b3973f3e)
opentelekomcloud_dns_recordset_v2.test_a: Creating...
  name:      "" => "testmikhail.com"
  records.#: "" => "1"
  records.0: "" => "80.158.7.123"
  region:    "" => "<computed>"
  ttl:       "" => "300"
  type:      "" => "A"
  zone_id:   "" => "ff80808261418b820161f704b3973f3e"
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still destroying... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27/ad4e5045-1a26-4750-91e0-be759f2ea4d7, 20s elapsed)
opentelekomcloud_dns_recordset_v2.test_a: Creation complete after 7s (ID: ff80808261418b820161f704b3973f3e/ff80808261418b820161f704c7d83f44)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still destroying... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27/ad4e5045-1a26-4750-91e0-be759f2ea4d7, 30s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still destroying... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27/ad4e5045-1a26-4750-91e0-be759f2ea4d7, 40s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Destruction complete after 46s
opentelekomcloud_compute_instance_v2.sd_test_instance: Destroying... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still destroying... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27, 10s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still destroying... (ID: b37bca77-dd2c-452a-81af-7c9cfeb83e27, 20s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Destruction complete after 22s
opentelekomcloud_compute_instance_v2.sd_test_instance: Creating...
  access_ip_v4:              "" => "<computed>"
  access_ip_v6:              "" => "<computed>"
  all_metadata.%:            "" => "<computed>"
  availability_zone:         "" => "eu-de-01"
  flavor_id:                 "" => "<computed>"
  flavor_name:               "" => "s1.medium"
  image_id:                  "" => "<computed>"
  image_name:                "" => "Community_Ubuntu_16.04_TSI_latest"
  key_pair:                  "" => "terraform_key"
  name:                      "" => "testmikhail.com"
  network.#:                 "" => "1"
  network.0.access_network:  "" => "false"
  network.0.fixed_ip_v4:     "" => "<computed>"
  network.0.fixed_ip_v6:     "" => "<computed>"
  network.0.floating_ip:     "" => "<computed>"
  network.0.mac:             "" => "<computed>"
  network.0.name:            "" => "<computed>"
  network.0.port:            "" => "<computed>"
  network.0.uuid:            "" => "ab9f2778-841b-4414-aa1e-3025ce04b820"
  region:                    "" => "<computed>"
  security_groups.#:         "" => "1"
  security_groups.821539756: "" => "testserver-secgrp"
  stop_before_destroy:       "" => "false"
  user_data:                 "" => "0806f93d55f31b85ed9ca24953948507fe7d9917"
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (10s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (20s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (30s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (40s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (50s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m0s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m10s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m20s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m30s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m40s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Still creating... (1m50s elapsed)
opentelekomcloud_compute_instance_v2.sd_test_instance: Creation complete after 1m51s (ID: 8fedfb02-39ac-4d5a-9ed3-fd71aa13e891)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Creating...
  instance_id: "" => "8fedfb02-39ac-4d5a-9ed3-fd71aa13e891"
  region:      "" => "<computed>"
  volume_id:   "" => "ad4e5045-1a26-4750-91e0-be759f2ea4d7"
opentelekomcloud_compute_floatingip_associate_v2.floatip_test_map: Creating...
  floating_ip: "" => "80.158.7.123"
  instance_id: "" => "8fedfb02-39ac-4d5a-9ed3-fd71aa13e891"
  region:      "" => "<computed>"
opentelekomcloud_compute_floatingip_associate_v2.floatip_test_map: Creation complete after 5s (ID: 80.158.7.123/8fedfb02-39ac-4d5a-9ed3-fd71aa13e891/)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (10s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (20s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (30s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Still creating... (40s elapsed)
opentelekomcloud_compute_volume_attach_v2.volume_attach: Creation complete after 40s (ID: 8fedfb02-39ac-4d5a-9ed3-fd71aa13e891/ad4e5045-1a26-4750-91e0-be759f2ea4d7)

Apply complete! Resources: 5 added, 0 changed, 5 destroyed.

**Comment by mvasilenko** [comment]
@28formica77 thank you for the answer
is the evs volume mounted on your instance while terraform trying to detach it?

i've researched a bit and it seems to be well known issue, that volume must be unmounted or instance must be stopped before detaching - other terraform provider have [`skip_destroy`](https://www.terraform.io/docs/providers/aws/r/volume_attachment.html#skip_destroy) flag as a workaround

the second possible solution - is to shutdown and unmount volume, before provisioning, it requires manual steps, it can be done in terraform also by different provisioner i think

**Comment by 28formica77** [comment]
Hi Mikhail,

Yes it is mounted. I am using your code. All I added was the EVS block and the az references. The disk gets attached and detached correctly for me. We allowed disks to be detached online about six months ago. The error you had looked more like terraform itself could not find the resource reference. Maybe you could check you have the current driver and run the job with debug so we can see the API calls and responses as well? You could email it to me. Or we could have a WebEx tomorrow?

Thanks Anthony.

**Comment by 28formica77** [comment]
TF_LOG_PATH=myfile TF_LOG=1 terraform apply ...

**Comment by mvasilenko** [comment]
yes, we can have webex, my email is in profile, what is yours?

**Comment by mvasilenko** [comment]
i've updated gist for `terraform apply` output

**Comment by mvasilenko** [comment]
The running instance can't detach mounted volume while it used.

This issue can be resolved by using specified `block_device` in `instance` section instead of volume and attachment `opentelekomcloud_compute_volume_attach_v2`:

```
  block_device {
      uuid             = "${data.opentelekomcloud_images_image_v2.sd_image.id}"
      #uuid = "d6944a41-5ec7-44a4-970e-ce330da390d2"

      source_type      = "image"
      destination_type = "volume"
      # 12gb is minimal image size for ubuntu
      volume_size      = "12"
      boot_index       = 0
      delete_on_termination = true
    }

  block_device {
      uuid             = "${opentelekomcloud_blockstorage_volume_v2.sd_test_data_disk.id}"
      source_type      = "volume"
      destination_type = "volume"
      boot_index       = 1
      # this is persistent volume with data, don't delete it on instance stop/update
      delete_on_termination = false
  }
```

Closing this. Thanks to @28formica77 for help
